// Generated by CoffeeScript 1.3.1
(function() {
  var initMap, position;

  position = function(lat, lng) {
    return new google.maps.LatLng(lat, lng);
  };

  initMap = function(container) {
    var map, marker, options;
    options = {
      zoom: 9,
      center: position(41.5, 2.3),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map($(container).get(0), options);
    marker = new google.maps.Marker({
      position: position(41.5, 1.7),
      icon: "https://developers.google.com/images/favicon.ico",
      clickable: true,
      title: "Title",
      cursor: "Cursor"
    });
    window.map = map;
    return window.marker = marker;
  };

  $(function() {
    initMap("#map_canvas");
    return $.ajax("/timetables.json").done(function(json) {
      var colors, coordinates, idx, line, path, st, _i, _len, _results;
      window.json = json;
      colors = ["#F00", "#0F0", "#00F"];
      _results = [];
      for (idx = _i = 0, _len = json.length; _i < _len; idx = ++_i) {
        line = json[idx];
        coordinates = (function() {
          var _j, _len1, _ref, _results1;
          _ref = line.stations;
          _results1 = [];
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            st = _ref[_j];
            _results1.push(position(st.lat, st.lon));
          }
          return _results1;
        })();
        path = new google.maps.Polyline({
          path: coordinates,
          strokeColor: colors[idx],
          strokeOpacity: 1.0,
          strokeWeight: 4
        });
        _results.push(path.setMap(map));
      }
      return _results;
    });
  });

}).call(this);
